/* This file was automatically generated by CasADi 3.7.0.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) plant_observe_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int long long int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_fmax CASADI_PREFIX(fmax)
#define casadi_fmin CASADI_PREFIX(fmin)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

casadi_real casadi_fmin(casadi_real x, casadi_real y) {
/* Pre-c99 compatibility */
#if __STDC_VERSION__ < 199901L
  return x<y ? x : y;
#else
  return fmin(x, y);
#endif
}

casadi_real casadi_fmax(casadi_real x, casadi_real y) {
/* Pre-c99 compatibility */
#if __STDC_VERSION__ < 199901L
  return x>y ? x : y;
#else
  return fmax(x, y);
#endif
}

static const casadi_int casadi_s0[3] = {27, 1, 1};
static const casadi_int casadi_s1[3] = {24, 1, 1};
static const casadi_int casadi_s2[3] = {45, 1, 1};

/* plant_observe:(x[27],u[24])->(z[45]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a00, a01, a02, a03, a04, a05, a06, a07, a08, a09, a10, a11;
  casadi_real a12, a13, a14, a15, a16, a17, a18, a19, a20, a21, a22, a23;
  casadi_real a24, a25, a26, a27, a28, a29, a30, a31, a32, a33, a34, a35;
  a00=40.;
  a01=arg[1]? arg[1][8] : 0;
  a00=(a00*a01);
  a01=1.1767980000000000e+02;
  a02=2.;
  a03=arg[0]? arg[0][5] : 0;
  a04=arg[0]? arg[0][3] : 0;
  a05=(a03*a04);
  a05=(a02*a05);
  a06=arg[0]? arg[0][6] : 0;
  a07=(a02*a06);
  a08=arg[0]? arg[0][4] : 0;
  a09=(a07*a08);
  a05=(a05-a09);
  a05=(a01*a05);
  a00=(a00+a05);
  a05=5.0000000000000000e-01;
  a09=101325.;
  a10=2.8814999999999998e+02;
  a11=-6.4999999999999997e-03;
  a12=520.;
  a13=arg[0]? arg[0][2] : 0;
  a12=(a12-a13);
  a11=(a11*a12);
  a11=(a10+a11);
  a10=(a11/a10);
  a13=5.2558798127166773e+00;
  a10=pow(a10,a13);
  a09=(a09*a10);
  a10=2.8705286999999998e+02;
  a10=(a10*a11);
  a10=(a09/a10);
  a13=(a05*a10);
  a14=arg[0]? arg[0][7] : 0;
  a15=casadi_sq(a06);
  a16=casadi_sq(a04);
  a17=casadi_sq(a08);
  a16=(a16+a17);
  a17=casadi_sq(a03);
  a16=(a16+a17);
  a15=(a15-a16);
  a16=casadi_sq(a04);
  a16=(a02*a16);
  a16=(a15+a16);
  a17=arg[1]? arg[1][21] : 0;
  a16=(a16*a17);
  a18=(a08*a04);
  a18=(a02*a18);
  a19=(a02*a06);
  a20=(a19*a03);
  a18=(a18+a20);
  a20=arg[1]? arg[1][22] : 0;
  a18=(a18*a20);
  a16=(a16+a18);
  a18=(a03*a04);
  a18=(a02*a18);
  a21=(a19*a08);
  a18=(a18-a21);
  a21=arg[1]? arg[1][23] : 0;
  a18=(a18*a21);
  a16=(a16+a18);
  a16=(a14-a16);
  a18=casadi_sq(a16);
  a22=arg[0]? arg[0][8] : 0;
  a23=(a04*a08);
  a23=(a02*a23);
  a24=(a19*a03);
  a23=(a23-a24);
  a23=(a23*a17);
  a24=casadi_sq(a08);
  a24=(a02*a24);
  a24=(a15+a24);
  a24=(a24*a20);
  a23=(a23+a24);
  a24=(a03*a08);
  a24=(a02*a24);
  a25=(a19*a04);
  a24=(a24+a25);
  a24=(a24*a21);
  a23=(a23+a24);
  a23=(a22-a23);
  a24=casadi_sq(a23);
  a18=(a18+a24);
  a24=arg[0]? arg[0][9] : 0;
  a25=(a04*a03);
  a25=(a02*a25);
  a26=(a19*a08);
  a25=(a25+a26);
  a25=(a25*a17);
  a17=(a08*a03);
  a17=(a02*a17);
  a19=(a19*a04);
  a17=(a17-a19);
  a17=(a17*a20);
  a25=(a25+a17);
  a17=casadi_sq(a03);
  a17=(a02*a17);
  a15=(a15+a17);
  a15=(a15*a21);
  a25=(a25+a15);
  a25=(a24-a25);
  a15=casadi_sq(a25);
  a18=(a18+a15);
  a15=1.0000000000000001e-09;
  a18=(a18+a15);
  a18=sqrt(a18);
  a13=(a13*a18);
  a13=(a13*a18);
  a21=(a05*a13);
  a17=1.0000000000000001e-01;
  a20=5.;
  a19=casadi_sq(a16);
  a19=(a19+a15);
  a19=sqrt(a19);
  a19=atan2(a25,a19);
  a20=(a20*a19);
  a17=(a17+a20);
  a20=(a21*a17);
  a15=sin(a19);
  a26=(a20*a15);
  a27=2.9999999999999999e-02;
  a28=4.4999999999999998e-02;
  a28=(a28*a17);
  a28=(a28*a17);
  a27=(a27+a28);
  a27=(a21*a27);
  a19=cos(a19);
  a28=(a27*a19);
  a26=(a26-a28);
  a00=(a00+a26);
  if (res[0]!=0) res[0][0]=a00;
  a26=(a03*a08);
  a26=(a02*a26);
  a07=(a07*a04);
  a26=(a26+a07);
  a26=(a01*a26);
  a07=-2.9999999999999999e-01;
  a28=(a23/a18);
  a17=1.;
  a28=casadi_fmin(a28,a17);
  a17=-1.;
  a28=casadi_fmax(a28,a17);
  a28=asin(a28);
  a07=(a07*a28);
  a07=(a21*a07);
  a26=(a26+a07);
  if (res[0]!=0) res[0][1]=a26;
  a07=casadi_sq(a06);
  a28=casadi_sq(a04);
  a17=casadi_sq(a08);
  a28=(a28+a17);
  a17=casadi_sq(a03);
  a28=(a28+a17);
  a07=(a07-a28);
  a28=casadi_sq(a03);
  a28=(a02*a28);
  a07=(a07+a28);
  a07=(a01*a07);
  a27=(a27*a15);
  a20=(a20*a19);
  a27=(a27+a20);
  a07=(a07-a27);
  if (res[0]!=0) res[0][2]=a07;
  a27=1.2000000000000000e-01;
  a20=arg[0]? arg[0][13] : 0;
  a19=arg[0]? arg[0][14] : 0;
  a20=(a20-a19);
  a20=(a05*a20);
  a27=(a27*a20);
  a20=-4.5000000000000001e-01;
  a19=arg[0]? arg[0][10] : 0;
  a15=(a02*a19);
  a28=(a02*a18);
  a15=(a15/a28);
  a20=(a20*a15);
  a27=(a27+a20);
  a27=(a13*a27);
  if (res[0]!=0) res[0][3]=a27;
  a20=2.5000000000000000e-01;
  a21=(a20*a21);
  a15=-9.0000000000000002e-01;
  a17=arg[0]? arg[0][17] : 0;
  a29=arg[0]? arg[0][18] : 0;
  a30=arg[0]? arg[0][19] : 0;
  a31=(a29+a30);
  a31=(a05*a31);
  a17=(a17+a31);
  a15=(a15*a17);
  a17=-8.;
  a31=arg[0]? arg[0][11] : 0;
  a20=(a20*a31);
  a20=(a20/a28);
  a17=(a17*a20);
  a15=(a15+a17);
  a21=(a21*a15);
  if (res[0]!=0) res[0][4]=a21;
  a15=-5.9999999999999998e-02;
  a29=(a29-a30);
  a29=(a05*a29);
  a15=(a15*a29);
  a29=-1.4999999999999999e-01;
  a30=arg[0]? arg[0][12] : 0;
  a17=(a02*a30);
  a17=(a17/a28);
  a29=(a29*a17);
  a15=(a15+a29);
  a13=(a13*a15);
  if (res[0]!=0) res[0][5]=a13;
  a15=0.;
  if (res[0]!=0) res[0][6]=a15;
  if (res[0]!=0) res[0][7]=a15;
  a29=9.8066499999999994e+00;
  if (res[0]!=0) res[0][8]=a29;
  a29=12.;
  if (res[0]!=0) res[0][9]=a29;
  a17=8.0000000000000004e-01;
  if (res[0]!=0) res[0][10]=a17;
  if (res[0]!=0) res[0][11]=a15;
  if (res[0]!=0) res[0][12]=a15;
  if (res[0]!=0) res[0][13]=a15;
  a28=1.2000000000000000e+00;
  if (res[0]!=0) res[0][14]=a28;
  if (res[0]!=0) res[0][15]=a15;
  if (res[0]!=0) res[0][16]=a15;
  if (res[0]!=0) res[0][17]=a15;
  a15=1.8999999999999999e+00;
  if (res[0]!=0) res[0][18]=a15;
  if (res[0]!=0) res[0][19]=a18;
  a20=(a03*a04);
  a20=(a02*a20);
  a32=(a02*a06);
  a33=(a32*a08);
  a20=(a20-a33);
  a33=(a01*a20);
  a00=(a00-a33);
  a00=(a00/a29);
  if (res[0]!=0) res[0][20]=a00;
  a33=(a03*a08);
  a33=(a02*a33);
  a34=(a32*a04);
  a33=(a33+a34);
  a34=(a01*a33);
  a26=(a26-a34);
  a26=(a26/a29);
  if (res[0]!=0) res[0][21]=a26;
  a06=casadi_sq(a06);
  a34=casadi_sq(a04);
  a35=casadi_sq(a08);
  a34=(a34+a35);
  a35=casadi_sq(a03);
  a34=(a34+a35);
  a06=(a06-a34);
  a34=casadi_sq(a03);
  a34=(a02*a34);
  a34=(a06+a34);
  a01=(a01*a34);
  a07=(a07-a01);
  a07=(a07/a29);
  if (res[0]!=0) res[0][22]=a07;
  a29=casadi_sq(a04);
  a29=(a02*a29);
  a29=(a06+a29);
  a29=(a29*a14);
  a01=(a04*a08);
  a01=(a02*a01);
  a35=(a32*a03);
  a01=(a01-a35);
  a01=(a01*a22);
  a29=(a29+a01);
  a01=(a04*a03);
  a01=(a02*a01);
  a35=(a32*a08);
  a01=(a01+a35);
  a01=(a01*a24);
  a29=(a29+a01);
  if (res[0]!=0) res[0][23]=a29;
  a29=(a08*a04);
  a29=(a02*a29);
  a01=(a32*a03);
  a29=(a29+a01);
  a29=(a29*a14);
  a01=casadi_sq(a08);
  a01=(a02*a01);
  a06=(a06+a01);
  a06=(a06*a22);
  a29=(a29+a06);
  a08=(a08*a03);
  a02=(a02*a08);
  a32=(a32*a04);
  a02=(a02-a32);
  a02=(a02*a24);
  a29=(a29+a02);
  if (res[0]!=0) res[0][24]=a29;
  a20=(a20*a14);
  a33=(a33*a22);
  a20=(a20+a33);
  a34=(a34*a24);
  a20=(a20+a34);
  if (res[0]!=0) res[0][25]=a20;
  if (res[0]!=0) res[0][26]=a12;
  a12=6.4939199999999997e-01;
  a20=arg[0]? arg[0][0] : 0;
  a34=6378137.;
  a20=(a20/a34);
  a12=(a12+a20);
  if (res[0]!=0) res[0][27]=a12;
  a12=-1.4061779999999999e+00;
  a20=arg[0]? arg[0][1] : 0;
  a34=5.0798774487696532e+06;
  a20=(a20/a34);
  a12=(a12+a20);
  if (res[0]!=0) res[0][28]=a12;
  if (res[0]!=0) res[0][29]=a11;
  if (res[0]!=0) res[0][30]=a10;
  if (res[0]!=0) res[0][31]=a09;
  a05=(a05*a10);
  a05=(a05*a18);
  a05=(a05*a18);
  if (res[0]!=0) res[0][32]=a05;
  a05=1.2500000000000000e+00;
  a15=(a15*a30);
  a18=(a31*a15);
  a28=(a28*a31);
  a10=(a30*a28);
  a18=(a18-a10);
  a27=(a27-a18);
  a05=(a05*a27);
  if (res[0]!=0) res[0][33]=a05;
  a05=8.3333333333333337e-01;
  a17=(a17*a19);
  a27=(a30*a17);
  a15=(a19*a15);
  a27=(a27-a15);
  a21=(a21-a27);
  a05=(a05*a21);
  if (res[0]!=0) res[0][34]=a05;
  a05=5.2631578947368418e-01;
  a28=(a19*a28);
  a17=(a31*a17);
  a28=(a28-a17);
  a13=(a13-a28);
  a05=(a05*a13);
  if (res[0]!=0) res[0][35]=a05;
  a05=1.0100000000000000e+00;
  a05=(a05*a19);
  a13=7.0699999999999999e-03;
  a13=(a13*a31);
  a05=(a05+a13);
  a13=5.2519999999999997e-03;
  a13=(a13*a30);
  a05=(a05+a13);
  a13=arg[0]? arg[0][21] : 0;
  a05=(a05+a13);
  a13=8.7000000000000001e-05;
  a28=arg[1]? arg[1][9] : 0;
  a28=(a13*a28);
  a05=(a05+a28);
  if (res[0]!=0) res[0][36]=a05;
  a05=-6.9579999999999998e-03;
  a05=(a05*a19);
  a28=9.9399999999999999e-01;
  a28=(a28*a31);
  a05=(a05+a28);
  a28=8.6477999999999989e-03;
  a28=(a28*a30);
  a05=(a05+a28);
  a28=arg[0]? arg[0][22] : 0;
  a05=(a05+a28);
  a28=arg[1]? arg[1][10] : 0;
  a28=(a13*a28);
  a05=(a05+a28);
  if (res[0]!=0) res[0][37]=a05;
  a05=-5.2675999999999990e-03;
  a05=(a05*a19);
  a19=-8.8130999999999991e-03;
  a19=(a19*a31);
  a05=(a05+a19);
  a19=1.0129999999999999e+00;
  a19=(a19*a30);
  a05=(a05+a19);
  a19=arg[0]? arg[0][23] : 0;
  a05=(a05+a19);
  a19=arg[1]? arg[1][11] : 0;
  a13=(a13*a19);
  a05=(a05+a13);
  if (res[0]!=0) res[0][38]=a05;
  a05=9.9199999999999999e-01;
  a05=(a05*a00);
  a13=-4.3648000000000003e-03;
  a13=(a13*a26);
  a05=(a05+a13);
  a13=-8.6303999999999999e-03;
  a13=(a13*a07);
  a05=(a05+a13);
  a13=arg[0]? arg[0][24] : 0;
  a05=(a05+a13);
  a13=9.7999999999999997e-04;
  a19=arg[1]? arg[1][12] : 0;
  a19=(a13*a19);
  a05=(a05+a19);
  if (res[0]!=0) res[0][39]=a05;
  a05=4.4483999999999999e-03;
  a05=(a05*a00);
  a19=1.0109999999999999e+00;
  a19=(a19*a26);
  a05=(a05+a19);
  a19=-6.1671000000000000e-03;
  a19=(a19*a07);
  a05=(a05+a19);
  a19=arg[0]? arg[0][25] : 0;
  a05=(a05+a19);
  a19=arg[1]? arg[1][13] : 0;
  a19=(a13*a19);
  a05=(a05+a19);
  if (res[0]!=0) res[0][40]=a05;
  a05=8.7434999999999978e-03;
  a05=(a05*a00);
  a00=6.1304999999999997e-03;
  a00=(a00*a26);
  a05=(a05+a00);
  a00=1.0049999999999999e+00;
  a00=(a00*a07);
  a05=(a05+a00);
  a00=arg[0]? arg[0][26] : 0;
  a05=(a05+a00);
  a00=arg[1]? arg[1][14] : 0;
  a13=(a13*a00);
  a05=(a05+a13);
  if (res[0]!=0) res[0][41]=a05;
  if (res[0]!=0) res[0][42]=a16;
  if (res[0]!=0) res[0][43]=a23;
  if (res[0]!=0) res[0][44]=a25;
  return 0;
}

CASADI_SYMBOL_EXPORT int plant_observe(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int plant_observe_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int plant_observe_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void plant_observe_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int plant_observe_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void plant_observe_release(int mem) {
}

CASADI_SYMBOL_EXPORT void plant_observe_incref(void) {
}

CASADI_SYMBOL_EXPORT void plant_observe_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int plant_observe_n_in(void) { return 2;}

CASADI_SYMBOL_EXPORT casadi_int plant_observe_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real plant_observe_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* plant_observe_name_in(casadi_int i) {
  switch (i) {
    case 0: return "x";
    case 1: return "u";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* plant_observe_name_out(casadi_int i) {
  switch (i) {
    case 0: return "z";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* plant_observe_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* plant_observe_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int plant_observe_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 2;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int plant_observe_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 2*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 1*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
