/* This file was automatically generated by CasADi 3.7.0.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) plant_observe_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int long long int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_fmax CASADI_PREFIX(fmax)
#define casadi_fmin CASADI_PREFIX(fmin)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

casadi_real casadi_fmin(casadi_real x, casadi_real y) {
/* Pre-c99 compatibility */
#if __STDC_VERSION__ < 199901L
  return x<y ? x : y;
#else
  return fmin(x, y);
#endif
}

casadi_real casadi_fmax(casadi_real x, casadi_real y) {
/* Pre-c99 compatibility */
#if __STDC_VERSION__ < 199901L
  return x>y ? x : y;
#else
  return fmax(x, y);
#endif
}

static const casadi_int casadi_s0[3] = {21, 1, 1};
static const casadi_int casadi_s1[3] = {9, 1, 1};
static const casadi_int casadi_s2[3] = {33, 1, 1};

/* plant_observe:(x[21],u[9])->(z[33]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a00, a01, a02, a03, a04, a05, a06, a07, a08, a09, a10, a11;
  casadi_real a12, a13, a14, a15, a16, a17, a18, a19, a20, a21, a22, a23;
  casadi_real a24, a25, a26;
  a00=40.;
  a01=arg[1]? arg[1][8] : 0;
  a00=(a00*a01);
  a01=1.1767980000000000e+02;
  a02=2.;
  a03=arg[0]? arg[0][5] : 0;
  a04=arg[0]? arg[0][3] : 0;
  a05=(a03*a04);
  a05=(a02*a05);
  a06=arg[0]? arg[0][6] : 0;
  a07=(a02*a06);
  a08=arg[0]? arg[0][4] : 0;
  a09=(a07*a08);
  a05=(a05-a09);
  a05=(a01*a05);
  a00=(a00+a05);
  a05=5.0000000000000000e-01;
  a09=101325.;
  a10=2.8814999999999998e+02;
  a11=-6.4999999999999997e-03;
  a12=520.;
  a13=arg[0]? arg[0][2] : 0;
  a12=(a12-a13);
  a11=(a11*a12);
  a11=(a10+a11);
  a10=(a11/a10);
  a13=5.2558798127166773e+00;
  a10=pow(a10,a13);
  a09=(a09*a10);
  a10=2.8705286999999998e+02;
  a10=(a10*a11);
  a10=(a09/a10);
  a13=(a05*a10);
  a14=arg[0]? arg[0][7] : 0;
  a15=casadi_sq(a14);
  a16=arg[0]? arg[0][8] : 0;
  a17=casadi_sq(a16);
  a15=(a15+a17);
  a17=arg[0]? arg[0][9] : 0;
  a18=casadi_sq(a17);
  a15=(a15+a18);
  a18=1.0000000000000001e-09;
  a15=(a15+a18);
  a15=sqrt(a15);
  a13=(a13*a15);
  a13=(a13*a15);
  a19=(a05*a13);
  a20=1.0000000000000001e-01;
  a21=5.;
  a22=casadi_sq(a14);
  a22=(a22+a18);
  a22=sqrt(a22);
  a22=atan2(a17,a22);
  a21=(a21*a22);
  a20=(a20+a21);
  a21=(a19*a20);
  a18=sin(a22);
  a23=(a21*a18);
  a24=2.9999999999999999e-02;
  a25=4.4999999999999998e-02;
  a25=(a25*a20);
  a25=(a25*a20);
  a24=(a24+a25);
  a24=(a19*a24);
  a22=cos(a22);
  a25=(a24*a22);
  a23=(a23-a25);
  a00=(a00+a23);
  if (res[0]!=0) res[0][0]=a00;
  a23=(a03*a08);
  a23=(a02*a23);
  a07=(a07*a04);
  a23=(a23+a07);
  a23=(a01*a23);
  a07=-2.9999999999999999e-01;
  a25=(a16/a15);
  a20=1.;
  a25=casadi_fmin(a25,a20);
  a20=-1.;
  a25=casadi_fmax(a25,a20);
  a25=asin(a25);
  a07=(a07*a25);
  a07=(a19*a07);
  a23=(a23+a07);
  if (res[0]!=0) res[0][1]=a23;
  a07=casadi_sq(a06);
  a25=casadi_sq(a04);
  a20=casadi_sq(a08);
  a25=(a25+a20);
  a20=casadi_sq(a03);
  a25=(a25+a20);
  a07=(a07-a25);
  a25=casadi_sq(a03);
  a25=(a02*a25);
  a07=(a07+a25);
  a07=(a01*a07);
  a24=(a24*a18);
  a21=(a21*a22);
  a24=(a24+a21);
  a07=(a07-a24);
  if (res[0]!=0) res[0][2]=a07;
  a24=1.2000000000000000e-01;
  a21=arg[0]? arg[0][13] : 0;
  a22=arg[0]? arg[0][14] : 0;
  a21=(a21-a22);
  a21=(a05*a21);
  a24=(a24*a21);
  a21=-4.5000000000000001e-01;
  a22=arg[0]? arg[0][10] : 0;
  a22=(a02*a22);
  a18=(a02*a15);
  a22=(a22/a18);
  a21=(a21*a22);
  a24=(a24+a21);
  a24=(a13*a24);
  if (res[0]!=0) res[0][3]=a24;
  a24=2.5000000000000000e-01;
  a19=(a24*a19);
  a21=-9.0000000000000002e-01;
  a22=arg[0]? arg[0][17] : 0;
  a25=arg[0]? arg[0][18] : 0;
  a20=arg[0]? arg[0][19] : 0;
  a26=(a25+a20);
  a26=(a05*a26);
  a22=(a22+a26);
  a21=(a21*a22);
  a22=-8.;
  a26=arg[0]? arg[0][11] : 0;
  a24=(a24*a26);
  a24=(a24/a18);
  a22=(a22*a24);
  a21=(a21+a22);
  a19=(a19*a21);
  if (res[0]!=0) res[0][4]=a19;
  a19=-5.9999999999999998e-02;
  a25=(a25-a20);
  a25=(a05*a25);
  a19=(a19*a25);
  a25=-1.4999999999999999e-01;
  a20=arg[0]? arg[0][12] : 0;
  a20=(a02*a20);
  a20=(a20/a18);
  a25=(a25*a20);
  a19=(a19+a25);
  a13=(a13*a19);
  if (res[0]!=0) res[0][5]=a13;
  a13=0.;
  if (res[0]!=0) res[0][6]=a13;
  if (res[0]!=0) res[0][7]=a13;
  a19=9.8066499999999994e+00;
  if (res[0]!=0) res[0][8]=a19;
  a19=12.;
  if (res[0]!=0) res[0][9]=a19;
  a25=8.0000000000000004e-01;
  if (res[0]!=0) res[0][10]=a25;
  if (res[0]!=0) res[0][11]=a13;
  if (res[0]!=0) res[0][12]=a13;
  if (res[0]!=0) res[0][13]=a13;
  a25=1.2000000000000000e+00;
  if (res[0]!=0) res[0][14]=a25;
  if (res[0]!=0) res[0][15]=a13;
  if (res[0]!=0) res[0][16]=a13;
  if (res[0]!=0) res[0][17]=a13;
  a13=1.8999999999999999e+00;
  if (res[0]!=0) res[0][18]=a13;
  if (res[0]!=0) res[0][19]=a15;
  a13=(a03*a04);
  a13=(a02*a13);
  a25=(a02*a06);
  a20=(a25*a08);
  a13=(a13-a20);
  a20=(a01*a13);
  a00=(a00-a20);
  a00=(a00/a19);
  if (res[0]!=0) res[0][20]=a00;
  a00=(a03*a08);
  a00=(a02*a00);
  a20=(a25*a04);
  a00=(a00+a20);
  a20=(a01*a00);
  a23=(a23-a20);
  a23=(a23/a19);
  if (res[0]!=0) res[0][21]=a23;
  a06=casadi_sq(a06);
  a23=casadi_sq(a04);
  a20=casadi_sq(a08);
  a23=(a23+a20);
  a20=casadi_sq(a03);
  a23=(a23+a20);
  a06=(a06-a23);
  a23=casadi_sq(a03);
  a23=(a02*a23);
  a23=(a06+a23);
  a01=(a01*a23);
  a07=(a07-a01);
  a07=(a07/a19);
  if (res[0]!=0) res[0][22]=a07;
  a07=casadi_sq(a04);
  a07=(a02*a07);
  a07=(a06+a07);
  a07=(a07*a14);
  a19=(a04*a08);
  a19=(a02*a19);
  a01=(a25*a03);
  a19=(a19-a01);
  a19=(a19*a16);
  a07=(a07+a19);
  a19=(a04*a03);
  a19=(a02*a19);
  a01=(a25*a08);
  a19=(a19+a01);
  a19=(a19*a17);
  a07=(a07+a19);
  if (res[0]!=0) res[0][23]=a07;
  a07=(a08*a04);
  a07=(a02*a07);
  a19=(a25*a03);
  a07=(a07+a19);
  a07=(a07*a14);
  a19=casadi_sq(a08);
  a19=(a02*a19);
  a06=(a06+a19);
  a06=(a06*a16);
  a07=(a07+a06);
  a08=(a08*a03);
  a02=(a02*a08);
  a25=(a25*a04);
  a02=(a02-a25);
  a02=(a02*a17);
  a07=(a07+a02);
  if (res[0]!=0) res[0][24]=a07;
  a13=(a13*a14);
  a00=(a00*a16);
  a13=(a13+a00);
  a23=(a23*a17);
  a13=(a13+a23);
  if (res[0]!=0) res[0][25]=a13;
  if (res[0]!=0) res[0][26]=a12;
  a12=6.4939199999999997e-01;
  a13=arg[0]? arg[0][0] : 0;
  a23=6378137.;
  a13=(a13/a23);
  a12=(a12+a13);
  if (res[0]!=0) res[0][27]=a12;
  a12=-1.4061779999999999e+00;
  a13=arg[0]? arg[0][1] : 0;
  a23=5.0798774487696532e+06;
  a13=(a13/a23);
  a12=(a12+a13);
  if (res[0]!=0) res[0][28]=a12;
  if (res[0]!=0) res[0][29]=a11;
  if (res[0]!=0) res[0][30]=a10;
  if (res[0]!=0) res[0][31]=a09;
  a05=(a05*a10);
  a05=(a05*a15);
  a05=(a05*a15);
  if (res[0]!=0) res[0][32]=a05;
  return 0;
}

CASADI_SYMBOL_EXPORT int plant_observe(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int plant_observe_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int plant_observe_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void plant_observe_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int plant_observe_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void plant_observe_release(int mem) {
}

CASADI_SYMBOL_EXPORT void plant_observe_incref(void) {
}

CASADI_SYMBOL_EXPORT void plant_observe_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int plant_observe_n_in(void) { return 2;}

CASADI_SYMBOL_EXPORT casadi_int plant_observe_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real plant_observe_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* plant_observe_name_in(casadi_int i) {
  switch (i) {
    case 0: return "x";
    case 1: return "u";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* plant_observe_name_out(casadi_int i) {
  switch (i) {
    case 0: return "z";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* plant_observe_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* plant_observe_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int plant_observe_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 2;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int plant_observe_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 2*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 1*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
