/* This file was automatically generated by CasADi 3.7.0.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) ctl_step_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int long long int
#endif

/* Add prefix to internal symbols */
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_fmax CASADI_PREFIX(fmax)
#define casadi_fmin CASADI_PREFIX(fmin)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_sq CASADI_PREFIX(sq)
#define casadi_zeros CASADI_PREFIX(zeros)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

casadi_real casadi_sq(casadi_real x) { return x*x;}

casadi_real casadi_fmax(casadi_real x, casadi_real y) {
/* Pre-c99 compatibility */
#if __STDC_VERSION__ < 199901L
  return x>y ? x : y;
#else
  return fmax(x, y);
#endif
}

casadi_real casadi_fmin(casadi_real x, casadi_real y) {
/* Pre-c99 compatibility */
#if __STDC_VERSION__ < 199901L
  return x<y ? x : y;
#else
  return fmin(x, y);
#endif
}

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

static const casadi_int casadi_s0[3] = {11, 1, 1};
static const casadi_int casadi_s1[3] = {2, 1, 1};
static const casadi_int casadi_s2[3] = {36, 1, 1};
static const casadi_int casadi_s3[3] = {8, 1, 1};
static const casadi_int casadi_s4[3] = {10, 1, 1};

static const casadi_real casadi_zeros[11] = 
  {0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0.};

/* ctl_step:(in[11],x[2],p[36])->(x_next[2],surface_cmd[8],ctl_signals[10]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i, j, k;
  casadi_real *rr, *w00=w+8, w01, w02, w04, w05, w06, w07, w08, w09, w10, w11;
  casadi_real w12, w13, w14, *w15=w+34, *w16=w+42, *w17=w+45, *w18=w+48, *w19=w+51, *w20=w+54, *w21=w+57, *w22=w+60, *w23=w+63;
  casadi_real *w24=w+66, *w25=w+90;
  const casadi_real *cs, *ct, *wr03;
  /* #0: @0 = input[1][0] */
  casadi_copy(arg[1], 2, w00);
  /* #1: @1 = @0[0] */
  for (rr=(&w01), cs=w00+0; cs!=w00+1; cs+=1) *rr++ = *cs;
  /* #2: @2 = input[2][7] */
  w02 = arg[2] ? arg[2][7] : 0;
  /* #3: @3 = input[0][0] */
  wr03 = arg[0] ? arg[0] : casadi_zeros;
  /* #4: @4 = @3[0] */
  w04 = wr03[0];
  /* #5: @5 = input[2][9] */
  w05 = arg[2] ? arg[2][9] : 0;
  /* #6: @4 = (@4*@5) */
  w04 *= w05;
  /* #7: @5 = @3[6] */
  w05 = wr03[6];
  /* #8: @6 = @3[3] */
  w06 = wr03[3];
  /* #9: @7 = (@5*@6) */
  w07  = (w05*w06);
  /* #10: @8 = @3[4] */
  w08 = wr03[4];
  /* #11: @9 = @3[5] */
  w09 = wr03[5];
  /* #12: @10 = (@8*@9) */
  w10  = (w08*w09);
  /* #13: @7 = (@7+@10) */
  w07 += w10;
  /* #14: @7 = (2.*@7) */
  w07 = (2.* w07 );
  /* #15: @10 = 1 */
  w10 = 1.;
  /* #16: @11 = sq(@6) */
  w11 = casadi_sq( w06 );
  /* #17: @12 = sq(@8) */
  w12 = casadi_sq( w08 );
  /* #18: @11 = (@11+@12) */
  w11 += w12;
  /* #19: @11 = (2.*@11) */
  w11 = (2.* w11 );
  /* #20: @10 = (@10-@11) */
  w10 -= w11;
  /* #21: @7 = atan2(@7,@10) */
  w07  = atan2(w07,w10);
  /* #22: @7 = (@4-@7) */
  w07  = (w04-w07);
  /* #23: @2 = (@2*@7) */
  w02 *= w07;
  /* #24: @7 = @3[7] */
  w07 = wr03[7];
  /* #25: @7 = (@2-@7) */
  w07  = (w02-w07);
  /* #26: @10 = @3[10] */
  w10 = wr03[10];
  /* #27: @11 = 0 */
  w11 = 0.;
  /* #28: @10 = fmax(@10,@11) */
  w10  = casadi_fmax(w10,w11);
  /* #29: @11 = (@7*@10) */
  w11  = (w07*w10);
  /* #30: @1 = (@1+@11) */
  w01 += w11;
  /* #31: @11 = input[2][5] */
  w11 = arg[2] ? arg[2][5] : 0;
  /* #32: @1 = fmin(@1,@11) */
  w01  = casadi_fmin(w01,w11);
  /* #33: @11 = (-@11) */
  w11 = (- w11 );
  /* #34: @1 = fmax(@1,@11) */
  w01  = casadi_fmax(w01,w11);
  /* #35: output[0][0] = @1 */
  if (res[0]) res[0][0] = w01;
  /* #36: @11 = @0[1] */
  for (rr=(&w11), cs=w00+1; cs!=w00+2; cs+=1) *rr++ = *cs;
  /* #37: @12 = input[2][8] */
  w12 = arg[2] ? arg[2][8] : 0;
  /* #38: @13 = @3[1] */
  w13 = wr03[1];
  /* #39: @14 = input[2][10] */
  w14 = arg[2] ? arg[2][10] : 0;
  /* #40: @13 = (@13*@14) */
  w13 *= w14;
  /* #41: @5 = (@5*@8) */
  w05 *= w08;
  /* #42: @9 = (@9*@6) */
  w09 *= w06;
  /* #43: @5 = (@5-@9) */
  w05 -= w09;
  /* #44: @5 = (2.*@5) */
  w05 = (2.* w05 );
  /* #45: @9 = 1 */
  w09 = 1.;
  /* #46: @5 = fmin(@5,@9) */
  w05  = casadi_fmin(w05,w09);
  /* #47: @9 = -1 */
  w09 = -1.;
  /* #48: @5 = fmax(@5,@9) */
  w05  = casadi_fmax(w05,w09);
  /* #49: @5 = asin(@5) */
  w05 = asin( w05 );
  /* #50: @5 = (@13-@5) */
  w05  = (w13-w05);
  /* #51: @12 = (@12*@5) */
  w12 *= w05;
  /* #52: @5 = @3[8] */
  w05 = wr03[8];
  /* #53: @5 = (@12-@5) */
  w05  = (w12-w05);
  /* #54: @10 = (@5*@10) */
  w10  = (w05*w10);
  /* #55: @11 = (@11+@10) */
  w11 += w10;
  /* #56: @10 = input[2][6] */
  w10 = arg[2] ? arg[2][6] : 0;
  /* #57: @11 = fmin(@11,@10) */
  w11  = casadi_fmin(w11,w10);
  /* #58: @10 = (-@10) */
  w10 = (- w10 );
  /* #59: @11 = fmax(@11,@10) */
  w11  = casadi_fmax(w11,w10);
  /* #60: output[0][1] = @11 */
  if (res[0]) res[0][1] = w11;
  /* #61: @15 = zeros(8x1) */
  casadi_clear(w15, 8);
  /* #62: @10 = input[2][12] */
  w10 = arg[2] ? arg[2][12] : 0;
  /* #63: @9 = input[2][13] */
  w09 = arg[2] ? arg[2][13] : 0;
  /* #64: @6 = input[2][14] */
  w06 = arg[2] ? arg[2][14] : 0;
  /* #65: @16 = horzcat(@10, @9, @6) */
  rr=w16;
  *rr++ = w10;
  *rr++ = w09;
  *rr++ = w06;
  /* #66: @16 = @16' */
  /* #67: @10 = input[2][15] */
  w10 = arg[2] ? arg[2][15] : 0;
  /* #68: @9 = input[2][16] */
  w09 = arg[2] ? arg[2][16] : 0;
  /* #69: @6 = input[2][17] */
  w06 = arg[2] ? arg[2][17] : 0;
  /* #70: @17 = horzcat(@10, @9, @6) */
  rr=w17;
  *rr++ = w10;
  *rr++ = w09;
  *rr++ = w06;
  /* #71: @17 = @17' */
  /* #72: @10 = input[2][18] */
  w10 = arg[2] ? arg[2][18] : 0;
  /* #73: @9 = input[2][19] */
  w09 = arg[2] ? arg[2][19] : 0;
  /* #74: @6 = input[2][20] */
  w06 = arg[2] ? arg[2][20] : 0;
  /* #75: @18 = horzcat(@10, @9, @6) */
  rr=w18;
  *rr++ = w10;
  *rr++ = w09;
  *rr++ = w06;
  /* #76: @18 = @18' */
  /* #77: @10 = input[2][21] */
  w10 = arg[2] ? arg[2][21] : 0;
  /* #78: @9 = input[2][22] */
  w09 = arg[2] ? arg[2][22] : 0;
  /* #79: @6 = input[2][23] */
  w06 = arg[2] ? arg[2][23] : 0;
  /* #80: @19 = horzcat(@10, @9, @6) */
  rr=w19;
  *rr++ = w10;
  *rr++ = w09;
  *rr++ = w06;
  /* #81: @19 = @19' */
  /* #82: @10 = input[2][24] */
  w10 = arg[2] ? arg[2][24] : 0;
  /* #83: @9 = input[2][25] */
  w09 = arg[2] ? arg[2][25] : 0;
  /* #84: @6 = input[2][26] */
  w06 = arg[2] ? arg[2][26] : 0;
  /* #85: @20 = horzcat(@10, @9, @6) */
  rr=w20;
  *rr++ = w10;
  *rr++ = w09;
  *rr++ = w06;
  /* #86: @20 = @20' */
  /* #87: @10 = input[2][27] */
  w10 = arg[2] ? arg[2][27] : 0;
  /* #88: @9 = input[2][28] */
  w09 = arg[2] ? arg[2][28] : 0;
  /* #89: @6 = input[2][29] */
  w06 = arg[2] ? arg[2][29] : 0;
  /* #90: @21 = horzcat(@10, @9, @6) */
  rr=w21;
  *rr++ = w10;
  *rr++ = w09;
  *rr++ = w06;
  /* #91: @21 = @21' */
  /* #92: @10 = input[2][30] */
  w10 = arg[2] ? arg[2][30] : 0;
  /* #93: @9 = input[2][31] */
  w09 = arg[2] ? arg[2][31] : 0;
  /* #94: @6 = input[2][32] */
  w06 = arg[2] ? arg[2][32] : 0;
  /* #95: @22 = horzcat(@10, @9, @6) */
  rr=w22;
  *rr++ = w10;
  *rr++ = w09;
  *rr++ = w06;
  /* #96: @22 = @22' */
  /* #97: @10 = input[2][33] */
  w10 = arg[2] ? arg[2][33] : 0;
  /* #98: @9 = input[2][34] */
  w09 = arg[2] ? arg[2][34] : 0;
  /* #99: @6 = input[2][35] */
  w06 = arg[2] ? arg[2][35] : 0;
  /* #100: @23 = horzcat(@10, @9, @6) */
  rr=w23;
  *rr++ = w10;
  *rr++ = w09;
  *rr++ = w06;
  /* #101: @23 = @23' */
  /* #102: @24 = horzcat(@16, @17, @18, @19, @20, @21, @22, @23) */
  rr=w24;
  for (i=0, cs=w16; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w17; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w18; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w19; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w20; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w21; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w22; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w23; i<3; ++i) *rr++ = *cs++;
  /* #103: @25 = @24' */
  for (i=0, rr=w25, cs=w24; i<8; ++i) for (j=0; j<3; ++j) rr[i+j*8] = *cs++;
  /* #104: @10 = input[2][0] */
  w10 = arg[2] ? arg[2][0] : 0;
  /* #105: @10 = (@10*@7) */
  w10 *= w07;
  /* #106: @7 = input[2][1] */
  w07 = arg[2] ? arg[2][1] : 0;
  /* #107: @7 = (@7*@1) */
  w07 *= w01;
  /* #108: @10 = (@10+@7) */
  w10 += w07;
  /* #109: @7 = 1 */
  w07 = 1.;
  /* #110: @10 = fmin(@10,@7) */
  w10  = casadi_fmin(w10,w07);
  /* #111: @7 = -1 */
  w07 = -1.;
  /* #112: @10 = fmax(@10,@7) */
  w10  = casadi_fmax(w10,w07);
  /* #113: @7 = input[2][2] */
  w07 = arg[2] ? arg[2][2] : 0;
  /* #114: @7 = (@7*@5) */
  w07 *= w05;
  /* #115: @5 = input[2][3] */
  w05 = arg[2] ? arg[2][3] : 0;
  /* #116: @5 = (@5*@11) */
  w05 *= w11;
  /* #117: @7 = (@7+@5) */
  w07 += w05;
  /* #118: @5 = 1 */
  w05 = 1.;
  /* #119: @7 = fmin(@7,@5) */
  w07  = casadi_fmin(w07,w05);
  /* #120: @5 = -1 */
  w05 = -1.;
  /* #121: @7 = fmax(@7,@5) */
  w07  = casadi_fmax(w07,w05);
  /* #122: @5 = input[2][4] */
  w05 = arg[2] ? arg[2][4] : 0;
  /* #123: @9 = @3[2] */
  w09 = wr03[2];
  /* #124: @6 = input[2][11] */
  w06 = arg[2] ? arg[2][11] : 0;
  /* #125: @9 = (@9*@6) */
  w09 *= w06;
  /* #126: @6 = @3[9] */
  w06 = wr03[9];
  /* #127: @6 = (@9-@6) */
  w06  = (w09-w06);
  /* #128: @5 = (@5*@6) */
  w05 *= w06;
  /* #129: @6 = 1 */
  w06 = 1.;
  /* #130: @5 = fmin(@5,@6) */
  w05  = casadi_fmin(w05,w06);
  /* #131: @6 = -1 */
  w06 = -1.;
  /* #132: @5 = fmax(@5,@6) */
  w05  = casadi_fmax(w05,w06);
  /* #133: @16 = vertcat(@10, @7, @5) */
  rr=w16;
  *rr++ = w10;
  *rr++ = w07;
  *rr++ = w05;
  /* #134: @15 = mac(@25,@16,@15) */
  for (i=0, rr=w15; i<1; ++i) for (j=0; j<8; ++j, ++rr) for (k=0, cs=w25+j, ct=w16+i*3; k<3; ++k) *rr += cs[k*8]**ct++;
  /* #135: output[1][0] = @15 */
  casadi_copy(w15, 8, res[1]);
  /* #136: output[2][0] = @4 */
  if (res[2]) res[2][0] = w04;
  /* #137: output[2][1] = @13 */
  if (res[2]) res[2][1] = w13;
  /* #138: output[2][2] = @2 */
  if (res[2]) res[2][2] = w02;
  /* #139: output[2][3] = @12 */
  if (res[2]) res[2][3] = w12;
  /* #140: output[2][4] = @9 */
  if (res[2]) res[2][4] = w09;
  /* #141: output[2][5] = @1 */
  if (res[2]) res[2][5] = w01;
  /* #142: output[2][6] = @11 */
  if (res[2]) res[2][6] = w11;
  /* #143: output[2][7] = @10 */
  if (res[2]) res[2][7] = w10;
  /* #144: output[2][8] = @7 */
  if (res[2]) res[2][8] = w07;
  /* #145: output[2][9] = @5 */
  if (res[2]) res[2][9] = w05;
  return 0;
}

CASADI_SYMBOL_EXPORT int ctl_step(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int ctl_step_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int ctl_step_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void ctl_step_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int ctl_step_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void ctl_step_release(int mem) {
}

CASADI_SYMBOL_EXPORT void ctl_step_incref(void) {
}

CASADI_SYMBOL_EXPORT void ctl_step_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int ctl_step_n_in(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_int ctl_step_n_out(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_real ctl_step_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* ctl_step_name_in(casadi_int i) {
  switch (i) {
    case 0: return "in";
    case 1: return "x";
    case 2: return "p";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* ctl_step_name_out(casadi_int i) {
  switch (i) {
    case 0: return "x_next";
    case 1: return "surface_cmd";
    case 2: return "ctl_signals";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* ctl_step_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* ctl_step_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s1;
    case 1: return casadi_s3;
    case 2: return casadi_s4;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int ctl_step_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 11;
  if (sz_res) *sz_res = 4;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 114;
  return 0;
}

CASADI_SYMBOL_EXPORT int ctl_step_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 11*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 4*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 114*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
